---
name: Spark SAS7BDAT Build & Test

on:
  pull_request:
    paths:
      - "src/**"
      - "build.sbt"
      - "project/**"
      - ".github/workflows/spark-sas7bdat*.yml"
  workflow_dispatch:

jobs:
  spark-sas7bdat-test:
    runs-on:
      group: dev
      labels: [self-hosted, dev]
    steps:

      - name: Aetion Common
        uses: aetion/actions@main

      - name: Run Tests and Package (Cross-compile all Scala versions)
        uses: aetion/actions/sbt@main
        with:
          sbtVersion: 1.9.8
          sbtCommand: -v "+clean" "+test" "+package"
          javaVersion: 17

      - name: Verify JARs Created
        run: |
          echo "*** Package JARs created: ***"
          ls -lh target/scala-*/spark-sas7bdat*.jar
